/*
 * Created on 7 oct. 2013 ( Time 10:16:40 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package dao;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "ARTICLE"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="ARTICLE", schema="ROOT" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Article.query1", query="SELECT x FROM Article x WHERE  " ),
//  @NamedQuery ( name="Article.query2", query="SELECT x FROM Article x WHERE  " )
// } )
public class Article implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="CODE", nullable=false, length=2)
    private String     code         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", nullable=false, length=12)
    private String     nom          ;

    @Column(name="PRIX", nullable=false)
    private double     prix         ;

    @Column(name="STOCK", nullable=false)
    private int        stock        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Article()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCode( String code )
    {
        this.code = code ;
    }
    public String getCode()
    {
        return this.code;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom )
    {
        this.nom = nom;
    }
    public String getNom()
    {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRIX ( DOUBLE ) 
    public void setPrix( double prix )
    {
        this.prix = prix;
    }
    public double getPrix()
    {
        return this.prix;
    }

    //--- DATABASE MAPPING : STOCK ( INTEGER ) 
    public void setStock( int stock )
    {
        this.stock = stock;
    }
    public int getStock()
    {
        return this.stock;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(code); 
        sb.append("|"); 
        sb.append(nom); 
        sb.append( "|" ); 
        sb.append(prix); 
        sb.append( "|" ); 
        sb.append(stock); 
        return sb.toString(); 
    }

}
