/*
 * Created on 7 oct. 2013 ( Time 10:16:40 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package test.persistence;


import mock.AdherentMock;

import org.junit.Assert;
import org.junit.Test;

import persistence.PersistenceServiceProvider;
import persistence.services.AdherentPersistence;
import dao.Adherent;

/**
 * JUnit test case for Adherent persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class AdherentPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Adherent persistence : delete + load ..." );
		
		AdherentPersistence service = PersistenceServiceProvider.getService(AdherentPersistence.class);
		
		AdherentMock mock = new AdherentMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(AdherentPersistence service, AdherentMock mock, String identifiant ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Adherent entity = service.load( identifiant );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( identifiant ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( identifiant );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
