/*
 * Created on 8 oct. 2013 ( Time 22:11:33 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package emn.association.persistence.services.jpa;

import emn.association.bean.Article ;
import emn.association.persistence.commons.jpa.GenericJpaService;
import emn.association.persistence.services.ArticlePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Article" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceJPA extends GenericJpaService<Article, String> implements ArticlePersistence {

	/**
	 * Constructor
	 */
	public ArticlePersistenceJPA() {
		super(Article.class);
	}

	public Article load( String code ) {
		return super.load( code );
	}

	public boolean delete( String code ) {
		return super.delete( code );
	}

	public boolean delete(Article entity) {
		if ( entity != null ) {
			return super.delete( entity.getCode() );
		}
		return false ;
	}

}
