
/*
 * Created on 8 oct. 2013 ( Time 22:11:33 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package emn.association.mock;

import java.util.LinkedList;
import java.util.List;

import emn.association.bean.Adherent ;
import emn.association.mock.tool.MockValues;

public class AdherentMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Adherent createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(255) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Adherent createInstance( String identifiant ) {
		Adherent entity = new Adherent();
		// Init Primary Key fields
		entity.setIdentifiant( identifiant) ;
		// Init Data fields
		entity.setMotdepasse( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setNomdefamille( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPrenom( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setRue( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setCodepostal( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setVille( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPays( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Adherent> createList(int count) {
		List<Adherent> list = new LinkedList<Adherent>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
