
/*
 * Created on 8 oct. 2013 ( Time 22:11:33 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package emn.association.mock;

import java.util.LinkedList;
import java.util.List;

import emn.association.bean.Article ;
import emn.association.mock.tool.MockValues;

public class ArticleMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Article createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(2) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Article createInstance( String code ) {
		Article entity = new Article();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(12) ) ; // java.lang.String 
		entity.setPrix( mockValues.nextDouble() ) ; // double 
		entity.setStock( mockValues.nextInteger() ) ; // int 
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Article> createList(int count) {
		List<Article> list = new LinkedList<Article>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
